import type { CityOption, DistrictOption } from '../types';
import busanImage from '../assets/cities/busan.webp';
import chungbukImage from '../assets/cities/chungbuk.webp';
import chungnamImage from '../assets/cities/chungnam.webp';
import daeguImage from '../assets/cities/daegu.webp';
import daejeonImage from '../assets/cities/daejeon.webp';
import gangwonImage from '../assets/cities/gangwon.webp';
import gwangjuImage from '../assets/cities/gwangju.webp';
import gyeongbukImage from '../assets/cities/gyeongbuk.webp';
import gyeonggiImage from '../assets/cities/gyeonggi.webp';
import gyeongnamImage from '../assets/cities/gyeongnam.webp';
import incheonImage from '../assets/cities/incheon.webp';
import jejuImage from '../assets/cities/jeju.webp';
import jeonbukImage from '../assets/cities/jeonbuk.webp';
import jeonnamImage from '../assets/cities/jeonnam.webp';
import sejongImage from '../assets/cities/sejong.webp';
import seoulImage from '../assets/cities/seoul.webp';
import ulsanImage from '../assets/cities/ulsan.webp';

export const DEFAULT_CITY_ID = 'seoul';

const createDistricts = (districts: readonly string[]): DistrictOption[] =>
  districts.map((name) => ({ name }));

const nestedDistricts: Record<string, readonly string[]> = {
  고양시: ['전체', '덕양구', '일산동구', '일산서구'],
  부천시: ['전체', '소사구', '오정구', '원미구'],
  성남시: ['전체', '분당구', '수정구', '중원구'],
  수원시: ['전체', '권선구', '영통구', '장안구', '팔달구'],
  안산시: ['전체', '단원구', '상록구'],
  안양시: ['전체', '동안구', '만안구'],
  용인시: ['전체', '기흥구', '수지구', '처인구'],
  화성시: ['전체', '동탄구', '만세구', '병점구', '효행구'],
  청주시: ['전체', '상당구', '서원구', '청원구', '흥덕구'],
  천안시: ['전체', '동남구', '서북구'],
  포항시: ['전체', '남구', '북구'],
  창원시: ['전체', '마산합포구', '마산회원구', '성산구', '의창구', '진해구'],
  전주시: ['전체', '덕진구', '완산구'],
};

const createNestedDistricts = (
  districts: readonly string[]
): DistrictOption[] =>
  districts.map((name) => ({
    name,
    subDistricts: nestedDistricts[name],
  }));

export const cityOptions: readonly CityOption[] = [
  {
    id: 'seoul',
    name: '서울',
    imageSrc: seoulImage,
    districts: createDistricts([
      '전체',
      '강남구',
      '강동구',
      '강북구',
      '강서구',
      '관악구',
      '광진구',
      '구로구',
      '금천구',
      '노원구',
      '도봉구',
      '동대문구',
      '동작구',
      '마포구',
      '서대문구',
      '서초구',
      '성동구',
      '성북구',
      '송파구',
      '양천구',
      '영등포구',
      '용산구',
      '은평구',
      '종로구',
      '중구',
      '중랑구',
    ]),
  },
  {
    id: 'busan',
    name: '부산',
    imageSrc: busanImage,
    districts: createDistricts([
      '전체',
      '강서구',
      '금정구',
      '기장군',
      '남구',
      '동구',
      '동래구',
      '부산진구',
      '북구',
      '사상구',
      '사하구',
      '서구',
      '수영구',
      '연제구',
      '영도구',
      '중구',
      '해운대구',
    ]),
  },
  {
    id: 'daegu',
    name: '대구',
    imageSrc: daeguImage,
    districts: createDistricts([
      '전체',
      '군위군',
      '남구',
      '달서구',
      '달성군',
      '동구',
      '북구',
      '서구',
      '수성구',
      '중구',
    ]),
  },
  {
    id: 'gwangju',
    name: '광주',
    imageSrc: gwangjuImage,
    districts: createDistricts(['전체', '광산구', '남구', '동구', '북구', '서구']),
  },
  {
    id: 'incheon',
    name: '인천',
    imageSrc: incheonImage,
    districts: createDistricts([
      '전체',
      '강화군',
      '계양구',
      '남동구',
      '동구',
      '미추홀구',
      '부평구',
      '서구',
      '연수구',
      '옹진군',
      '중구',
    ]),
  },
  {
    id: 'daejeon',
    name: '대전',
    imageSrc: daejeonImage,
    districts: createDistricts(['전체', '대덕구', '동구', '서구', '유성구', '중구']),
  },
  {
    id: 'ulsan',
    name: '울산',
    imageSrc: ulsanImage,
    districts: createDistricts(['전체', '남구', '동구', '북구', '울주군', '중구']),
  },
  {
    id: 'sejong',
    name: '세종',
    imageSrc: sejongImage,
    districts: createDistricts(['전체']),
  },
  {
    id: 'gyeonggi',
    name: '경기',
    imageSrc: gyeonggiImage,
    districts: createNestedDistricts([
      '전체',
      '가평군',
      '고양시',
      '과천시',
      '광명시',
      '광주시',
      '구리시',
      '군포시',
      '김포시',
      '남양주시',
      '동두천시',
      '부천시',
      '성남시',
      '수원시',
      '시흥시',
      '안산시',
      '안성시',
      '안양시',
      '양주시',
      '양평군',
      '여주시',
      '연천군',
      '오산시',
      '용인시',
      '의왕시',
      '의정부시',
      '이천시',
      '파주시',
      '평택시',
      '포천시',
      '하남시',
      '화성시',
    ]),
  },
  {
    id: 'gangwon',
    name: '강원',
    imageSrc: gangwonImage,
    districts: createDistricts([
      '전체',
      '강릉시',
      '고성군',
      '동해시',
      '삼척시',
      '속초시',
      '양구군',
      '양양군',
      '영월군',
      '원주시',
      '인제군',
      '정선군',
      '철원군',
      '춘천시',
      '태백시',
      '평창군',
      '홍천군',
      '화천군',
      '횡성군',
    ]),
  },
  {
    id: 'chungbuk',
    name: '충북',
    imageSrc: chungbukImage,
    districts: createNestedDistricts([
      '전체',
      '괴산군',
      '단양군',
      '보은군',
      '영동군',
      '옥천군',
      '음성군',
      '제천시',
      '증평군',
      '진천군',
      '청주시',
      '충주시',
    ]),
  },
  {
    id: 'chungnam',
    name: '충남',
    imageSrc: chungnamImage,
    districts: createNestedDistricts([
      '전체',
      '계룡시',
      '공주시',
      '금산군',
      '논산시',
      '당진시',
      '보령시',
      '부여군',
      '서산시',
      '서천군',
      '아산시',
      '예산군',
      '천안시',
      '청양군',
      '태안군',
      '홍성군',
    ]),
  },
  {
    id: 'gyeongbuk',
    name: '경북',
    imageSrc: gyeongbukImage,
    districts: createNestedDistricts([
      '전체',
      '경산시',
      '경주시',
      '고령군',
      '구미시',
      '김천시',
      '문경시',
      '봉화군',
      '상주시',
      '성주군',
      '안동시',
      '영덕군',
      '영양군',
      '영주시',
      '영천시',
      '예천군',
      '울릉군',
      '울진군',
      '의성군',
      '청도군',
      '청송군',
      '칠곡군',
      '포항시',
    ]),
  },
  {
    id: 'gyeongnam',
    name: '경남',
    imageSrc: gyeongnamImage,
    districts: createNestedDistricts([
      '전체',
      '거제시',
      '거창군',
      '고성군',
      '김해시',
      '남해군',
      '밀양시',
      '사천시',
      '산청군',
      '양산시',
      '의령군',
      '진주시',
      '창녕군',
      '창원시',
      '통영시',
      '하동군',
      '함안군',
      '함양군',
      '합천군',
    ]),
  },
  {
    id: 'jeonbuk',
    name: '전북',
    imageSrc: jeonbukImage,
    districts: createNestedDistricts([
      '전체',
      '고창군',
      '군산시',
      '김제시',
      '남원시',
      '무주군',
      '부안군',
      '순창군',
      '완주군',
      '익산시',
      '임실군',
      '장수군',
      '전주시',
      '정읍시',
      '진안군',
    ]),
  },
  {
    id: 'jeonnam',
    name: '전남',
    imageSrc: jeonnamImage,
    districts: createDistricts([
      '전체',
      '강진군',
      '고흥군',
      '곡성군',
      '광양시',
      '구례군',
      '나주시',
      '담양군',
      '목포시',
      '무안군',
      '보성군',
      '순천시',
      '신안군',
      '여수시',
      '영광군',
      '영암군',
      '완도군',
      '장성군',
      '장흥군',
      '진도군',
      '함평군',
      '해남군',
      '화순군',
    ]),
  },
  {
    id: 'jeju',
    name: '제주',
    imageSrc: jejuImage,
    districts: createDistricts(['전체', '서귀포시', '제주시']),
  },
] as const;
