import courseImage from '../../yeogido-course/assets/courseimage.svg';

import type { LikedItem } from '../types';

/**
 * 좋아요 목록 API(GET /api/v1/users/me/likes) 연동 전까지 화면 확인용으로 쓰는
 * 임시 데이터. 연동 시 이 파일을 지우고 응답을 LikedItem으로 매핑하면 된다.
 */
export const MOCK_LIKED_ITEMS: LikedItem[] = [
  {
    id: 1,
    category: 'COURSE',
    title: '묵호 혼자 여행 코스',
    thumbnailUrl: courseImage,
    duration: '2박 3일',
    startDate: null,
    endDate: null,
    location: '뚜벅이',
    companion: '혼자',
    region: '부산',
    detailType: null,
    hashtags: ['summer', 'nature', 'sea'],
    likedAt: '2026-07-24T20:15:00',
  },
  {
    id: 2,
    category: 'COURSE',
    title: '묵호 혼자 여행 코스',
    thumbnailUrl: courseImage,
    duration: '2박 3일',
    startDate: null,
    endDate: null,
    location: '뚜벅이',
    companion: '혼자',
    region: '순천',
    detailType: null,
    hashtags: ['summer', 'nature', 'sea'],
    likedAt: '2026-07-23T18:02:00',
  },
  {
    id: 3,
    category: 'COURSE',
    title: '묵호 혼자 여행 코스',
    thumbnailUrl: courseImage,
    duration: '2박 3일',
    startDate: null,
    endDate: null,
    location: '뚜벅이',
    companion: '혼자',
    region: '부여',
    detailType: null,
    hashtags: ['summer', 'nature', 'sea'],
    likedAt: '2026-07-22T09:41:00',
  },
  {
    id: 4,
    category: 'COURSE',
    title: '묵호 혼자 여행 코스',
    thumbnailUrl: courseImage,
    duration: '2박 3일',
    startDate: null,
    endDate: null,
    location: '뚜벅이',
    companion: '혼자',
    region: '대구',
    detailType: null,
    hashtags: ['summer', 'nature', 'sea'],
    likedAt: '2026-07-21T13:27:00',
  },
  {
    id: 5,
    category: 'EVENT',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '축제',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-24T11:08:00',
  },
  {
    id: 6,
    category: 'EVENT',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '체험',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-20T15:33:00',
  },
  {
    id: 7,
    category: 'EVENT',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '전시',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-19T10:12:00',
  },
  {
    id: 8,
    category: 'EVENT',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '공연',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-18T21:45:00',
  },
  {
    id: 9,
    category: 'PLACE',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '음식점',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-17T12:20:00',
  },
  {
    id: 10,
    category: 'PLACE',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '카페 및 베이커리',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-16T08:55:00',
  },
  {
    id: 11,
    category: 'PLACE',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '지역명소',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-15T19:30:00',
  },
  {
    id: 12,
    category: 'PLACE',
    title: '양평수박축제',
    thumbnailUrl: null,
    duration: null,
    startDate: '2026.07',
    endDate: '2026.07',
    location: '경기도 양평군',
    companion: null,
    region: null,
    detailType: '체험 및 활동',
    hashtags: ['summer', 'nature', 'experience'],
    likedAt: '2026-07-14T14:05:00',
  },
];
